export const REQUEST_AUTH = 'REQUEST_AUTH';

export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_ROUTINE = 'GET_ROUTINE';

export const GET_USER_JOURNAL = 'GET_USER_JOURNAL';
export const CREATE_NEW_NOTE = 'CREATE_NEW_NOTE';
export const EDIT_NOTE = 'EDIT_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const SET_NOTE_CREATION = 'SET_NOTE_CREATION';
export const RESET_NOTE_CREATION = 'RESET_NOTE_CREATION';
export const SET_CREATING_NEW_NOTE = 'SET_CREATING_NEW_NOTE';
export const SET_SELECTED_NOTE = 'SET_SELECTED_NOTE';
export const SHIFT_PAGE = 'SHIFT_PAGE';

export const TRAINING_SET_COUNTDOWN_INTERVAL =
  'TRAINING_SET_COUNTDOWN_INTERVAL';
export const TRAINING_SET_COUNTDOWN = 'TRAINING_SET_COUNTDOWN';
export const TRAINING_SET_WORKOUT_ACTIVE = 'TRAINING_SET_WORKOUT_ACTIVE';
export const TRAINING_SET_CURRENT_EXERCISE_INDEX =
  'TRAINING_SET_CURRENT_EXERCISE_INDEX';
export const TRAINING_SET_FULL_WORKOUT = 'TRAINING_SET_FULL_WORKOUT';
