export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_JOURNAL = 'GET_USER_JOURNAL';

export const TRAINING_SET_COUNTDOWN_INTERVAL =
  'TRAINING_SET_COUNTDOWN_INTERVAL';
export const TRAINING_SET_COUNTDOWN = 'TRAINING_SET_COUNTDOWN';
export const TRAINING_SET_WORKOUT_ACTIVE = 'TRAINING_SET_WORKOUT_ACTIVE';
export const TRAINING_SET_CURRENT_EXERCISE_INDEX =
  'TRAINING_SET_CURRENT_EXERCISE_INDEX';
export const TRAINING_SET_FULL_WORKOUT = 'TRAINING_SET_FULL_WORKOUT';
